version: "3.9"
services:
  app:
    image: grpc-go
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "url"
    env_file  :
      - .env
    profiles:
      - db
  redis:
    image: redis
    container_name: redis
    environment:
      REDIS_HOST: "localhost"
      REDIS_PORT: "6379"
      STORAGE: redis
    profiles:
      - db
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    profiles:
      - db
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  in_memory:
    container_name: in_memory
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    profiles:
      - memory
    volumes:
      - .:/app/